@baseUrl = http://localhost:3000

POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "email": "asd@asd.com",
    "password": "asddsa"
}


###
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "email": "asdf@asdf.com",
    "password": "asdffdsa"
}

###
GET {{baseUrl}}/auth/whoami

###
POST {{baseUrl}}/auth/signout

###
GET {{baseUrl}}/auth/3


###
GET {{baseUrl}}/auth?email=a@b.com

###
DELETE  {{baseUrl}}/auth/2

###
PATCH  {{baseUrl}}/auth/3
Content-Type: application/json

{
    "email": "a@b.com"
}

# ###
# GET {{baseUrl}}/auth/colors/blue

# ###
# GET {{baseUrl}}/auth/colors
